    # HTTP Server middleware environment
    # Available values:
    #   dev
    #       development environment
    #   prod
    #       production environment
    #
    # Defaults to: prod
middleware: dev