swagger: '2.0'

info:
  version: '1'
  title: Device admission
  description: |
    An API for device admission handling. Intended for internal use.

basePath: '/api/0.1.0/'
host: 'mender-device-adm:8080'

schemes:
  - http

paths:
  /devices:
    delete:
      summary: Delete device data sets
      description: Removes device authentication data sets
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
          format: Bearer [token]
          description: Contains the JWT token issued by the User Administration and Authentication Service.
        - name: device_id
          in: query
          description: Delete all auth sets owned by given device
          required: true
          type: string
      responses:
        204:
          description: Authentication data sets removed.
        400:
          description: |
            Invalid parameters. See error message for details.
          schema:
            $ref: "#/definitions/Error"
        404:
         description: The device authentication data set was not found.
         schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error.
          schema:
            $ref: "#/definitions/Error"
  /devices/{id}:
    delete:
      summary: Remove device authentication data set
      description: Removes all device authentication data set data.
      parameters:
        - name: id
          in: path
          description: device authentication data set identifier
          required: true
          type: string
      responses:
        204:
          description: The device authentication data set was removed.
        404:
         description: The device authentication data set was not found.
         schema:
           $ref: "#/definitions/Error"
        500:
          description: Internal server error.
          schema:
           $ref: "#/definitions/Error"
definitions:
  Error:
    description: Error descriptor.
    type: object
    properties:
      error:
        description: Description of the error.
        type: string
      request_id:
        description: Request ID (same as in X-MEN-RequestID header).
        type: string
    example:
      application/json:
          error: "device not found"
          request_id: "f7881e82-0492-49fb-b459-795654e7188a"
